# Generated by Django 6.0.1 on 2026-01-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='password',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
