# Generated by Django 6.0.1 on 2026-01-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_model',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'Bike'), ('CAR', 'Car'), ('AUTO', 'Auto')], max_length=20),
        ),
    ]
