# Generated by Django 6.0.1 on 2026-01-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0006_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
