# Generated by Django 6.0.1 on 2026-01-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0007_ride_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='user_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
