# Generated by Django 6.0.1 on 2026-01-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0009_riderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('RIDER', 'Rider'), ('ADMIN', 'Admin')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
