# Generated by Django 6.0.1 on 2026-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0010_riderprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('AUTO', 'Auto')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
