# Generated by Django 6.0.1 on 2026-02-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0012_ride_pickup_latitude_ride_pickup_longitude_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='drop_latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
